import { Component } from '@angular/core';
import { ThemeService } from './core/theme.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  navItems = [
    { label: 'Dashboard', icon: 'space_dashboard', route: '/' },
    { label: 'Exams', icon: 'assignment', route: '/exams' },
    { label: 'Certificates', icon: 'workspace_premium', route: '/certificates' },
    { label: 'Uploads', icon: 'upload_file', route: '/uploads' },
    { label: 'People', icon: 'groups', route: '/people' }
  ];
  operationGroups = [
    {
      label: 'Offline paper scans',
      value: 7,
      details: [
        'INS-102: 3 new scans uploaded today.',
        'INS-207: 2 scans pending validation.',
        'QA-330: 2 scans waiting for leader review.'
      ]
    },
    {
      label: 'Certificate PDFs',
      value: 12,
      details: [
        '8 files generated by system in this week.',
        '3 files are pending digital signature.',
        '1 file failed upload checksum and needs re-upload.'
      ]
    },
    {
      label: 'Leader approvals',
      value: 4,
      details: [
        'a.nguyen: waiting approval for MOB-201.',
        'b.tran: waiting approval for EMB-104.',
        'h.vo: waiting approval for DOC-210.',
        'c.le: overdue approval for MOB-201.'
      ]
    }
  ];

  constructor(readonly themeService: ThemeService) {}

  toggleTheme(): void {
    this.themeService.toggle();
  }
}
